import { ReviewerFixture } from './types';

export const reviewerFixtures: ReviewerFixture[] = [
  {
    id: 'app-nahom',
    channel: 'web',
    synthetic: false,
    metadata: {
      companyName: 'ናሆም የኤሌክትሮኒክስ ጥገና (Nahom Electronics Repair)',
      businessType: 'የኤሌክትሮኒክስ ጥገና (Electronics Micro-Soldering)',
      region: 'አዲስ አበባ (+251 911 123456)',
      yearsInOperation: 3,
      language: 'am',
      submissionDate: '2026-08-30',
      licensePhotoUrl: '/demo/license-nahom.jpg',
      workshopPhotoUrl: '/demo/workshop-nahom.jpg',
    },
    input: {
      sales_growth_pct: 60,
      total_employees: 3,
      uniqueness: 'different_from_competitors',
      market_served: 'import_substituting',
      local_sourcing_pct: 30,
      ownership: 'neither',
      women_employee_pct: 0,
      youth_employee_pct: 66,
      expected_results_count: 3,
      job_count: 3, // 3 new jobs created (Assistant Technician, Receptionist, Intern)
      investment_readiness: 30,
      management_team_size: 3,
      impact_category: 'both_social_env',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-001',
    channel: 'web',
    synthetic: true,
    metadata: {
      companyName: 'Hiwot Eco-Textiles PLC',
      businessType: 'Textile & Garment',
      region: 'Oromia (Bishoftu)',
      yearsInOperation: 6,
      language: 'am',
      submissionDate: '2026-08-29',
      licensePhotoUrl: '/demo/license-hiwot.jpg',
      workshopPhotoUrl: '/demo/workshop-hiwot.jpg',
    },
    input: {
      sales_growth_pct: 60,
      total_employees: 25,
      uniqueness: 'new_in_ethiopia',
      market_served: 'international',
      local_sourcing_pct: 80,
      ownership: 'women_owned',
      women_employee_pct: 60,
      youth_employee_pct: 55,
      expected_results_count: 3,
      job_count: 450,
      investment_readiness: 30,
      management_team_size: 4,
      impact_category: 'green_business_model',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-002',
    channel: 'telegram',
    synthetic: true,
    metadata: {
      companyName: 'Abyssinia Leather Craft',
      businessType: 'Leather & Footwear',
      region: 'Addis Ababa',
      yearsInOperation: 4,
      language: 'en',
      submissionDate: '2026-08-28',
      licensePhotoUrl: '/demo/license-abyssinia.jpg',
      workshopPhotoUrl: '/demo/workshop-abyssinia.jpg',
    },
    input: {
      sales_growth_pct: 40,
      total_employees: 15,
      uniqueness: 'different_from_competitors',
      market_served: 'import_substituting',
      local_sourcing_pct: 50,
      ownership: 'women_managed',
      women_employee_pct: 45,
      youth_employee_pct: 30,
      expected_results_count: 2,
      job_count: 250,
      investment_readiness: 22,
      management_team_size: 3,
      impact_category: 'both_social_env',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-003',
    channel: 'web',
    synthetic: true,
    metadata: {
      companyName: 'Tana Agro Processing Enterprise',
      businessType: 'Agriculture & Food',
      region: 'Amhara (Bahir Dar)',
      yearsInOperation: 3,
      language: 'am',
      submissionDate: '2026-08-29',
    },
    input: {
      sales_growth_pct: 20,
      total_employees: 8,
      uniqueness: 'essential',
      market_served: 'local_only',
      local_sourcing_pct: 30,
      ownership: 'neither',
      women_employee_pct: 20,
      youth_employee_pct: 15,
      expected_results_count: 1,
      job_count: 150,
      investment_readiness: 18,
      management_team_size: 2,
      impact_category: 'either_social_or_env',
      legally_registered_and_years: true,
      privately_owned: true,
    },
    incompleteFields: ['growth_indicators.sales_etb.2023'],
  },
  {
    id: 'app-004',
    channel: 'telegram',
    synthetic: true,
    metadata: {
      companyName: 'Red Sea Metal Works (Unregistered)',
      businessType: 'Metal Manufacturing',
      region: 'Dire Dawa',
      yearsInOperation: 1,
      language: 'en',
      submissionDate: '2026-08-27',
    },
    input: {
      sales_growth_pct: 10,
      total_employees: 4,
      uniqueness: 'no_unique',
      market_served: 'local_only',
      local_sourcing_pct: 10,
      ownership: 'neither',
      women_employee_pct: 5,
      youth_employee_pct: 5,
      expected_results_count: 1,
      job_count: 50,
      investment_readiness: 10,
      management_team_size: 1,
      impact_category: 'neither',
      legally_registered_and_years: false, // Triggers E1 exclusion
      privately_owned: true,
    },
  },
  {
    id: 'app-005',
    channel: 'web',
    synthetic: true,
    metadata: {
      companyName: 'Oromia Solar & Bio-Energy Solutions',
      businessType: 'Renewable Energy',
      region: 'Oromia (Adama)',
      yearsInOperation: 7,
      language: 'om',
      submissionDate: '2026-08-29',
      licensePhotoUrl: '/demo/license-oromia-solar.jpg',
      workshopPhotoUrl: '/demo/workshop-oromia-solar.jpg',
    },
    input: {
      sales_growth_pct: 55,
      total_employees: 30,
      uniqueness: 'new_in_ethiopia',
      market_served: 'international',
      local_sourcing_pct: 70,
      ownership: 'women_owned',
      women_employee_pct: 70,
      youth_employee_pct: 60,
      expected_results_count: 3,
      job_count: 500,
      investment_readiness: 35,
      management_team_size: 5,
      impact_category: 'green_business_model',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-006',
    channel: 'telegram',
    synthetic: true,
    metadata: {
      companyName: 'Sidama Coffee Processors Union',
      businessType: 'Agro-processing',
      region: 'Sidama (Hawassa)',
      yearsInOperation: 5,
      language: 'en',
      submissionDate: '2026-08-29',
    },
    input: {
      sales_growth_pct: 45,
      total_employees: 20,
      uniqueness: 'different_from_competitors',
      market_served: 'import_substituting',
      local_sourcing_pct: 60,
      ownership: 'women_managed',
      women_employee_pct: 50,
      youth_employee_pct: 40,
      expected_results_count: 3,
      job_count: 350,
      investment_readiness: 28,
      management_team_size: 4,
      impact_category: 'both_social_env',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-007',
    channel: 'web',
    synthetic: true,
    metadata: {
      companyName: 'Entoto Bamboo Furniture & Craft',
      businessType: 'Wood & Furniture',
      region: 'Addis Ababa',
      yearsInOperation: 3,
      language: 'am',
      submissionDate: '2026-08-28',
    },
    input: {
      sales_growth_pct: 30,
      total_employees: 12,
      uniqueness: 'essential',
      market_served: 'local_only',
      local_sourcing_pct: 40,
      ownership: 'neither',
      women_employee_pct: 25,
      youth_employee_pct: 20,
      expected_results_count: 2,
      job_count: 200,
      investment_readiness: 20,
      management_team_size: 3,
      impact_category: 'either_social_or_env',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-008',
    channel: 'telegram',
    synthetic: true,
    metadata: {
      companyName: 'Rift Valley Eco-Tourism & Lodge',
      businessType: 'Tourism & Service',
      region: 'Oromia (Ziway)',
      yearsInOperation: 8,
      language: 'om',
      submissionDate: '2026-08-30',
      licensePhotoUrl: '/demo/license-riftvalley.jpg',
      workshopPhotoUrl: '/demo/premises-riftvalley.jpg',
    },
    input: {
      sales_growth_pct: 70,
      total_employees: 40,
      uniqueness: 'new_in_ethiopia',
      market_served: 'international',
      local_sourcing_pct: 90,
      ownership: 'women_owned',
      women_employee_pct: 80,
      youth_employee_pct: 70,
      expected_results_count: 3,
      job_count: 600,
      investment_readiness: 40,
      management_team_size: 6,
      impact_category: 'green_business_model',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-009',
    channel: 'web',
    synthetic: true,
    metadata: {
      companyName: 'State-Owned Chemical Supplies (SOE)',
      businessType: 'Chemicals',
      region: 'Oromia (Mojo)',
      yearsInOperation: 12,
      language: 'en',
      submissionDate: '2026-08-25',
    },
    input: {
      sales_growth_pct: 15,
      total_employees: 6,
      uniqueness: 'no_unique',
      market_served: 'local_only',
      local_sourcing_pct: 15,
      ownership: 'neither',
      women_employee_pct: 10,
      youth_employee_pct: 10,
      expected_results_count: 1,
      job_count: 100,
      investment_readiness: 12,
      management_team_size: 2,
      impact_category: 'neither',
      legally_registered_and_years: true,
      privately_owned: false, // Triggers E2 exclusion (State-owned)
    },
  },
  {
    id: 'app-010',
    channel: 'telegram',
    synthetic: true,
    metadata: {
      companyName: 'Bole Women Garment Cooperative',
      businessType: 'Textile & Garment',
      region: 'Addis Ababa',
      yearsInOperation: 8,
      language: 'am',
      submissionDate: '2026-08-29',
    },
    input: {
      sales_growth_pct: 50,
      total_employees: 22,
      uniqueness: 'different_from_competitors',
      market_served: 'import_substituting',
      local_sourcing_pct: 55,
      ownership: 'women_managed',
      women_employee_pct: 55,
      youth_employee_pct: 45,
      expected_results_count: 2,
      job_count: 320,
      investment_readiness: 25,
      management_team_size: 4,
      impact_category: 'both_social_env',
      legally_registered_and_years: true,
      privately_owned: true,
    },
    contradiction: 'Claimed 8 years in operation, but license document issue date indicates registration 2 years ago. Needs physical verification.',
  },
  {
    id: 'app-011',
    channel: 'web',
    synthetic: true,
    metadata: {
      companyName: 'Abay Sanitation & Water Tech',
      businessType: 'Water & Sanitation',
      region: 'Amhara (Gondar)',
      yearsInOperation: 4,
      language: 'am',
      submissionDate: '2026-08-28',
    },
    input: {
      sales_growth_pct: 25,
      total_employees: 10,
      uniqueness: 'essential',
      market_served: 'local_only',
      local_sourcing_pct: 35,
      ownership: 'neither',
      women_employee_pct: 20,
      youth_employee_pct: 15,
      expected_results_count: 1,
      job_count: 180,
      investment_readiness: 16,
      management_team_size: 2,
      impact_category: 'either_social_or_env',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-012',
    channel: 'telegram',
    synthetic: true,
    metadata: {
      companyName: 'Danakil Clean Energy Innovations',
      businessType: 'Clean Technology',
      region: 'Afar (Semera)',
      yearsInOperation: 5,
      language: 'en',
      submissionDate: '2026-08-30',
      licensePhotoUrl: '/demo/license-danakil.jpg',
      workshopPhotoUrl: '/demo/workshop-danakil.jpg',
    },
    input: {
      sales_growth_pct: 65,
      total_employees: 35,
      uniqueness: 'new_in_ethiopia',
      market_served: 'international',
      local_sourcing_pct: 85,
      ownership: 'women_owned',
      women_employee_pct: 75,
      youth_employee_pct: 65,
      expected_results_count: 3,
      job_count: 550,
      investment_readiness: 38,
      management_team_size: 5,
      impact_category: 'green_business_model',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-013',
    channel: 'web',
    synthetic: true,
    metadata: {
      companyName: 'ዓለም ሶላር እና ሃይድሮ ቴክኖሎጂ (Alem Solar Tech)',
      businessType: 'Renewable Energy & Irrigation',
      region: 'Sidama (Hawassa)',
      yearsInOperation: 5,
      language: 'am',
      submissionDate: '2026-08-30',
      licensePhotoUrl: '/demo/license-alem.jpg',
      workshopPhotoUrl: '/demo/workshop-alem.jpg',
    },
    input: {
      sales_growth_pct: 52,
      total_employees: 18,
      uniqueness: 'different_from_competitors',
      market_served: 'import_substituting',
      local_sourcing_pct: 60,
      ownership: 'women_managed',
      women_employee_pct: 40,
      youth_employee_pct: 55,
      expected_results_count: 3,
      job_count: 320,
      investment_readiness: 32,
      management_team_size: 4,
      impact_category: 'green_business_model',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-014',
    channel: 'telegram',
    synthetic: true,
    metadata: {
      companyName: 'ታየ የቆዳ ውጤቶች እና ጫማ መሥሪያ (Taye Leather Works)',
      businessType: 'Leather & Footwear',
      region: 'Addis Ababa (Merkato)',
      yearsInOperation: 4,
      language: 'am',
      submissionDate: '2026-08-30',
      licensePhotoUrl: '/demo/license-taye.jpg',
      workshopPhotoUrl: '/demo/workshop-taye.jpg',
    },
    input: {
      sales_growth_pct: 38,
      total_employees: 8,
      uniqueness: 'essential',
      market_served: 'local_only',
      local_sourcing_pct: 75,
      ownership: 'neither',
      women_employee_pct: 35,
      youth_employee_pct: 60,
      expected_results_count: 2,
      job_count: 180,
      investment_readiness: 24,
      management_team_size: 3,
      impact_category: 'both_social_env',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
  {
    id: 'app-015',
    channel: 'web',
    synthetic: true,
    metadata: {
      companyName: 'ሰላም የወተት እና እርሻ ምርቶች ማቀናበሪያ (Selam Dairy Processing)',
      businessType: 'Agro-processing',
      region: 'Amhara (Debre Birhan)',
      yearsInOperation: 6,
      language: 'am',
      submissionDate: '2026-08-30',
      licensePhotoUrl: '/demo/license-selam.jpg',
      workshopPhotoUrl: '/demo/workshop-selam.jpg',
    },
    input: {
      sales_growth_pct: 48,
      total_employees: 14,
      uniqueness: 'different_from_competitors',
      market_served: 'import_substituting',
      local_sourcing_pct: 90,
      ownership: 'women_owned',
      women_employee_pct: 50,
      youth_employee_pct: 45,
      expected_results_count: 3,
      job_count: 280,
      investment_readiness: 30,
      management_team_size: 3,
      impact_category: 'green_business_model',
      legally_registered_and_years: true,
      privately_owned: true,
    },
  },
];